version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gocritic
    - misspell
  settings:
    gosec:
      excludes:
        - G204  # subprocess launch - needed for git interaction
  exclusions:
    paths:
      - vendor

formatters:
  enable:
    - gofmt
