version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gocritic
    - misspell

linters-settings:
  gosec:
    excludes:
      - G204  # subprocess launch - needed for git interaction

issues:
  exclude-dirs:
    - vendor

formatters:
  enable:
    - gofmt
