version: 2

project_name: stringer

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/stringer
    binary: stringer
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.Version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"

# Homebrew tap auto-publish
# Requires a HOMEBREW_TAP_TOKEN secret in the repository settings:
#   - Create a GitHub PAT (classic) with 'repo' scope
#   - The PAT must have write access to davetashner/homebrew-tap
#   - Add it as a repository secret named HOMEBREW_TAP_TOKEN
brews:
  - repository:
      owner: davetashner
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/davetashner/stringer"
    description: "Codebase archaeology tool that mines git repos for actionable Beads issues"
    license: "MIT"
    folder: Formula
    test: |
      system "#{bin}/stringer", "version"
    install: |
      bin.install "stringer"

release:
  github:
    owner: davetashner
    name: stringer
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"
